# Generated by Django 6.0 on 2026-01-03 14:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', max_length=10, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号/工号')),
                ('college', models.CharField(blank=True, max_length=50, verbose_name='学院')),
                ('major_class', models.CharField(blank=True, max_length=50, verbose_name='专业班级')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系方式')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='模板名称')),
                ('type', models.CharField(choices=[('guide', '实训指导书'), ('plan', '实训教案'), ('report', '实训报告')], default='report', max_length=20, verbose_name='模板类型')),
                ('content_structure', models.JSONField(default=list, verbose_name='模板结构(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建教师')),
            ],
            options={
                'verbose_name': '文档模板',
                'verbose_name_plural': '文档模板',
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('target_class', models.CharField(max_length=50, verbose_name='目标班级')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('finished', '已结束')], default='draft', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发布教师')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reporttemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '实训任务',
                'verbose_name_plural': '实训任务',
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_data', models.JSONField(default=dict, verbose_name='报告内容(JSON)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成绩')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教师评语')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('returned', '被退回'), ('graded', '已评分')], default='draft', max_length=20, verbose_name='报告状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingtask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '学生实训报告',
                'verbose_name_plural': '学生实训报告',
                'unique_together': {('task', 'student')},
            },
        ),
    ]
