# Generated by Django 6.0 on 2026-01-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'verbose_name': '教学资源库', 'verbose_name_plural': '教学资源库'},
        ),
        migrations.AlterModelOptions(
            name='studentreport',
            options={'verbose_name': '学生报告'},
        ),
        migrations.AlterModelOptions(
            name='trainingtask',
            options={'verbose_name': '实训任务'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '系统用户'},
        ),
        migrations.AddField(
            model_name='studentreport',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True, verbose_name='AI评分建议'),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='reference_materials',
            field=models.ManyToManyField(blank=True, related_name='tasks_as_reference', to='core.reporttemplate', verbose_name='关联参考资料'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='content_structure',
            field=models.JSONField(default=list, verbose_name='文档结构(JSON)'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文档名称'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='type',
            field=models.CharField(choices=[('material', '📚 教学材料'), ('guide', '🧭 实训指导书'), ('plan', '📋 实训教案'), ('report', '📝 实训报告')], default='report', max_length=20, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_as_homework', to='core.reporttemplate', verbose_name='作业模板'),
        ),
    ]
