# Generated by Django 6.0 on 2026-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reporttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='task_details',
            field=models.JSONField(default=dict, verbose_name='实训详情数据'),
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='description',
            field=models.TextField(blank=True, verbose_name='任务备注'),
        ),
    ]
