# Generated by Django 6.0 on 2026-01-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trainingtask_task_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='附件(旧)'),
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/attachments/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.studentreport', verbose_name='所属报告')),
            ],
        ),
    ]
